version: "3.8"

services:
  database:
    image: postgres:15.2-alpine3.17
    volumes:
      - ./database/data:/var/lib/postgresql/data
    env_file:
      - ./database/.env

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8080:8080

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
