version: "3.8"

services:
  database:
    image: postgres:15.2-alpine3.17
    volumes:
      - ./database/data:/var/lib/postgresql/data
    env_file:
      - ./database/.env

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8080:8080

  backend:
    image: maven:3.9.1-eclipse-temurin-17-alpine
    working_dir: /app
    volumes:
      - ./backend:/app/
    command: mvn spring-boot:run
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app/
    entrypoint: sh ./entrypoint.sh
    ports:
      - 4200:4200
